name: run monitor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 # schedule:
 #    - cron: "*/5 * * * *"
  watch:
    types: [ started ]  #测试用 点击star就会运行
#1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -o app
      - name: Test
        run: go test -v ./...
      - name: Run
        env:
          LNG: ${{ secrets.LNG }}
          LAT: ${{ secrets.LAT }}
          BARK_ID_1: ${{ secrets.BARK_ID_1 }}
          BARK_ID_2: ${{ secrets. BARK_ID_2 }}
  #  station_id: 5cb00a3ed033a1d82a8b4569
     #     conf.StationId: 5cb00a3ed033a1d82a8b4569
    #      argConf.StationId: 5cb00a3ed033a1d82a8b4569
      #    URL: ${{ secrets.URL }}  #可以使用远程配置文件 如https://xxx.com/config.yaml 
        run: ./app  -p=$URL -lng=$LNG -lat=$LAT  -m=1 -i -b=$BARK_ID_1 -b=$BARK_ID_2
        



